export const getDefaultSoldItemsFilters = () => ({
    order_id: "",
    title: "",
    category: null,
    min_quantity: "",
    max_quantity: "",
    min_price: "",
    max_price: "",
    min_volume: "",
    max_volume: "",
    product_code: "",
    afterbuy_account: null,
    afterbuy_id: "",
    min_date: "",
    max_date: "",
});
